application_status_api:
    resource: ../../src/ApplicationStatus/Infrastructure/Controller/Api
    prefix: 'api/application-status'
    type: annotation

post_api:
    resource: ../../src/Post/Infrastructure/Controller/Api
    prefix: '/api/posts'
    type: annotation
